In [1]:
import emachine_v2 as em
import importlib
import numpy as np
import matplotlib.pyplot as plt
from Centraliser import TensorProductGroup as tpg
importlib.reload(em)
from emachine_v2 import even_process, golden_mean, pprint

In [2]:
P = 0.4
em1 = even_process(P)
em2 = golden_mean(P)
print("Even process:")
print(em1.A)
print("Golden mean:")
print(em2.A)

Even process:
[[[0.63245553 0.        ]
  [0.         0.        ]]

 [[0.         0.77459667]
  [1.         0.        ]]]
Golden mean:
[[[0.         0.63245553]
  [0.         0.        ]]

 [[0.77459667 0.        ]
  [1.         0.        ]]]


In [3]:
ham_ep = em1.parent_hamiltonian(3, 3)
ham_gm = em2.parent_hamiltonian(3, 3)
pjt_ep = em1.orthogonal_projector(3)
pjt_gm = em2.orthogonal_projector(3)
em2.sun_symmetry(ham_gm)


SYMMETRIC GENERATORS ANALYSIS

⚠️  No symmetry found: The null space is empty.



array([], dtype=float64)

In [ ]:
em_com = em.EMachine(em1.A & em2.A)
print(em_com.A)

state = em_com.to_ground_space(3,np.array([[1,2,0,0],[3,4,0,0],[0,0,1,2],[0,0,3,4]]))
print(state)
#em_com.sun_symmetry()

[[[0.63245553 0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.63245553]
  [0.         0.         0.         0.        ]]

 [[0.         0.77459667 0.         0.        ]
  [1.         0.         0.         0.        ]
  [0.         0.         0.77459667 0.        ]
  [0.         0.         1.         0.        ]]]
[0.86817915 1.09039293 0.         1.68122169 1.09039293 5.04504525
 1.68122169 4.22307367]
